export const ModalActionTypes = {
    ENABLE_MODAL: 'ENABLE_MODAL',
    DISABLE_MODAL: 'DISBALE_MODAL',
    ENABLE_EDIT_MODAL: 'ENABLE_EDIT_MODAL',
    DISABLE_EDIT_MODAL: 'DISABLE_EDIT_MODAL',
    ENABLE_ASSIGN_MODAL: 'ENABLE_ASSIGN_MODAL',
    DISABLE_ASSIGN_MODAL: 'DISABLE_ASSIGN_MODAL'
}