export const ModalActionTypes = {
    ENABLE_CREATE_MODAL: 'ENABLE_CREATE_MODAL',
    DISABLE_CREATE_MODAL: 'DISABLE_CREATE_MODAL',
    ENABLE_EDIT_MODAL: 'ENABLE_EDIT_MODAL',
    DISABLE_EDIT_MODAL: 'DISABLE_EDIT_MODAL',
    ENABLE_ASSIGN_MODAL: 'ENABLE_ASSIGN_MODAL',
    DISABLE_ASSIGN_MODAL: 'DISABLE_ASSIGN_MODAL'
}