export const TicketActionTypes = {
    FETCH_TICKET_DATA_START: 'FETCH_TICKET_DATA_START',
    ADD_EXISTING_TICKETS_TO_STATE: 'ADD_EXISTING_TICKETS_TO_STATE',
    ADD_NEW_TICKET: 'ADD_NEW_TICKET',
    ADD_NEW_TICKET_TO_STATE: 'ADD_NEW_TICKET_TO_STATE',
    UPDATE_TICKET: 'UPDATE_TICKET',
    UPDATE_TICKET_IN_STATE: 'UPDATE_TICKET_IN_STATE',
    START_LOADING: 'START_LOADING',
    FETCH_TICKET_DATA_SUCCESS: 'FETCH_TICKET_DATA_SUCCESS',
    FETCH_TICKET_DATA_FAILURE: 'FETCH_TICKET_DATA_FAILURE',
    ADD_NEW_TICKET_SUCCESS: 'ADD_NEW_TICKET_SUCCESS',
    ADD_NEW_TICKET_FAILURE: 'ADD_NEW_TICKET_FAILURE',
    UPDATE_TICKET_SUCCESS: 'UPDATE_TICKET_SUCCESS',
    UPDATE_TICKET_FAILURE: 'UPDATE_TICKET_FAILURE',
    UPDATE_SEARCH_FIELD: 'UPDATE_SEARCH_FIELD',
    ADD_TO_FIREBASE: 'ADD_TO_FIREBASE'
}