export const TicketActionTypes = {
    ADD_NEW_TICKET: 'ADD_NEW_TICKET',
    FETCH_TICKET_DATA_START: 'FETCH_TICKET_DATA_START',
    FETCH_TICKET_DATA_SUCCESS: 'FETCH_TICKET_DATA_SUCCESS',
    FETCH_TICKET_DATA_FAILURE: 'FETCH_TICKET_DATA_FAILURE'
}