export const TicketActionTypes = {
    FETCH_TICKET_DATA_START: 'FETCH_TICKET_DATA_START',
    ADD_EXISTING_TICKETS_TO_STATE: 'ADD_EXISTING_TICKETS_TO_STATE',
    ADD_NEW_TICKET: 'ADD_NEW_TICKET',
    SET_LOADING: 'SET_LOADING',
    FETCH_TICKET_DATA_SUCCESS: 'FETCH_TICKET_DATA_SUCCESS',
    FETCH_TICKET_DATA_FAILURE: 'FETCH_TICKET_DATA_FAILURE'
}