export const UserActionTypes = {
    FETCH_USER_DATA_START: 'FETCH_USER_DATA_START',
    ADD_EXISTING_USERS_TO_STATE: 'ADD_EXISTING_USERS_TO_STATE',
    START_LOADING: 'START_LOADING',
    FETCH_USER_DATA_SUCCESS: 'FETCH_USER_DATA_SUCCESS',
    FETCH_USER_DATA_FAILURE: 'FETCH_USER_DATA_FAILURE'
}